### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by wolverineks** [EdgeApp/edge-core-js#295]
im getting `Cannot read property 'toUpperCase' of undefined` when trying to pin or password login
this came right after i crashed my node app during infinite loop
only a single account

**Comment by wolverineks** [comment]
something to do with 
https://github.com/EdgeApp/edge-core-js/blob/63567a4982404f729ad8dd8b568d57cfc2d29468/src/core/account/account-files.js#L67

**Comment by wolverineks** [comment]
```bash
TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.parse$1 [as parse] (index.js:137)
    at eval (account-files.js:38)
    at Array.forEach (<anonymous>)
    at eval (account-files.js:36)
    at async Promise.all (/index 0)
    at async Promise.all (/index 1)
    at async Object.loadAllWalletStates (account-files.js:80)
    at async Promise.all (/index 1)
    at async loadAllFiles (account-pixie.js:36)
    at async Object.update (account-pixie.js:43)
```

**Comment by wolverineks** [comment]
is `account.disklet["Wallets"]` used for anything?
i tried putting files there, i think the account might have tried reading them for some other purpose?

**Comment by swansontec** [comment]
Yes, the core uses the `Wallets` folder to hold wallet settings. If you put files in there that don't match the expected format, then of course you will have problems.

Our policy is that, if something causes us to ever lose a private key, we prevent the account from making further logins, both to stop any further damage and to escalate the problem to the highest level of support. This has never actually happened, as far as we can tell. Since the Airbitz app used the `Wallets` folder to store keys, I believe returning an error at login is in-line with our policies on this issue.

**Comment by wolverineks** [comment]
so, blowing away `account.disklet["Wallets"]` means all the keys are permanently destroyed?

**Comment by swansontec** [comment]
Removing the `Wallets` folder would lose any keys created by Airbitz, if this is an older account from that app. Edge stores keys in another location.

Since our storage is Git, it is actually possible to clone the repo, revert any bad commits, and re-push. You need to know the sync key, which you can get from `account.keys`, and then try `git clone https://git-eusa.edge.app/repos/<syncKey>`. Use git commands to revert any bad commits, and then push the `master` branch back to that URL.
